https://medium.com/pursuitnotes/multiple-linear-regression-model-in-7-steps-with-python-c6f40c0a527

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:

from google.colab import drive
drive.mount("Multiple_regression")

Mounted at Multiple_regression


In [3]:

dataset=pd.read_csv('/content/Multiple_regression/MyDrive/Supervised and Unsupervised machine learning/Supervised Machine Learning/50_Startups.csv')
dataset.head(10)


R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [4]:

x=dataset.iloc[:,:-1].values # or x=dataset.drop('State',axis=1)
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [5]:

y=dataset.iloc[:,4]
y


0     192261.83
1     191792.06
2     191050.39
3     182901.99
4     166187.94
5     156991.12
6     156122.51
7     155752.60
8     152211.77
9     149759.96
10    146121.95
11    144259.40
12    141585.52
13    134307.35
14    132602.65
15    129917.04
16    126992.93
17    125370.37
18    124266.90
19    122776.86
20    118474.03
21    111313.02
22    110352.25
23    108733.99
24    108552.04
25    107404.34
26    105733.54
27    105008.31
28    103282.38
29    101004.64
30     99937.59
31     97483.56
32     97427.84
33     96778.92
34     96712.80
35     96479.51
36     90708.19
37     89949.14
38     81229.06
39     81005.76
40     78239.91
41     77798.83
42     71498.49
43     69758.98
44     65200.33
45     64926.08
46     49490.75
47     42559.73
48     35673.41
49     14681.40
Name: Profit, dtype: float64

In [6]:
x[:,3]

array(['New York', 'California', 'Florida', 'New York', 'Florida',
       'New York', 'California', 'Florida', 'New York', 'California',
       'Florida', 'California', 'Florida', 'California', 'Florida',
       'New York', 'California', 'New York', 'Florida', 'New York',
       'California', 'New York', 'Florida', 'Florida', 'New York',
       'California', 'Florida', 'New York', 'Florida', 'New York',
       'Florida', 'New York', 'California', 'Florida', 'California',
       'New York', 'Florida', 'California', 'New York', 'California',
       'California', 'Florida', 'California', 'New York', 'California',
       'New York', 'Florida', 'California', 'New York', 'California'],
      dtype=object)

In [7]:

from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
x[:,3]=labelencoder.fit_transform(x[:,3])


In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
import statsmodels.api as sm

# Use LabelEncoder for the categorical variable

In [9]:
#https://stackoverflow.com/questions/59476165/typeerror-init-got-an-unexpected-keyword-argument-categorical-features
ct = ColumnTransformer([("State", OneHotEncoder(), [1])], remainder = 'passthrough')
X = ct.fit_transform(x)

# Male/Female
labelencoder_X = LabelEncoder()
x[:, 2] = labelencoder_X.fit_transform(x[:, 2])

In [10]:
x.shape

(50, 4)

In [30]:
x.ndim

2

In [12]:

#avoiding the dummy variable trap
x=x[:,1:]#to avoid dummy variable trap we delete one column that is (California)
x


array([[136897.8, 47, 2],
       [151377.59, 46, 0],
       [101145.55, 45, 1],
       [118671.85, 44, 2],
       [91391.77, 43, 1],
       [99814.71, 42, 2],
       [147198.87, 10, 0],
       [145530.06, 40, 1],
       [148718.95, 39, 2],
       [108679.17, 38, 0],
       [110594.11, 24, 1],
       [91790.61, 25, 0],
       [127320.38, 26, 1],
       [135495.07, 27, 0],
       [156547.42, 28, 1],
       [122616.84, 29, 2],
       [121597.55, 30, 0],
       [145077.58, 31, 2],
       [114175.79, 32, 1],
       [153514.11, 0, 2],
       [113867.3, 34, 0],
       [153773.43, 35, 2],
       [122782.75, 36, 1],
       [105751.03, 37, 1],
       [99281.34, 13, 2],
       [139553.16, 12, 0],
       [144135.98, 11, 1],
       [127864.55, 41, 2],
       [182645.56, 9, 1],
       [153032.06, 8, 2],
       [115641.28, 7, 1],
       [152701.92, 6, 2],
       [129219.61, 5, 0],
       [103057.49, 23, 1],
       [157693.92, 22, 0],
       [85047.44, 21, 2],
       [127056.21, 20, 1],
       [51283.

# **Split the dataset**

In [13]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=0)


# Fit the model

In [14]:

from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)
y_pred=regressor.predict(x_test)


In [28]:
print('Train Score: ', regressor.score(x_train, y_train))  
print('Test Score: ', regressor.score(x_test, y_test))  

Train Score:  0.6203890946082304
Test Score:  0.2557218607565932


In [15]:
x.shape

(50, 3)

In [16]:
x[0].shape

(3,)

In [17]:
x[1].shape

(3,)

In [18]:


x=np.append(arr=np.ones((50,1)).astype(int),values=x,axis=1)



In [19]:
x[0]

array([1, 136897.8, 47, 2], dtype=object)

In [20]:
x.shape

(50, 4)

In [21]:
x.ndim

2

In [24]:

x_opt=x[:,[0,1,2,3]]#copy the index 0 to 3 from x in x_opt


https://statisticsbyjim.com/regression/interpret-coefficients-p-values-regression/

https://statisticsbyjim.com/regression/interpret-coefficients-p-values-regression/

In [25]:
#https://stackoverflow.com/questions/33833832/building-multi-regression-model-throws-error-pandas-data-cast-to-numpy-dtype-o
#OLS: ordinary least square
#Optimal X contains the highly impacted independent variables
#OLS: Oridnary Least Square Class. endog is the dependent variable, #exog is the number of observations

x_opt=x[:,[0,1,2,3]]#copy the index 0 to 3 from x in x_opt
regressor_OLS=sm.OLS(endog=y,exog=x_opt.astype(float)).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.579
Model:                            OLS   Adj. R-squared:                  0.551
Method:                 Least Squares   F-statistic:                     21.06
Date:                Wed, 17 May 2023   Prob (F-statistic):           9.89e-09
Time:                        09:19:58   Log-Likelihood:                -579.05
No. Observations:                  50   AIC:                             1166.
Df Residuals:                      46   BIC:                             1174.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.508e+04   1.88e+04      1.337      0.188   -1.27e+04    6.29e+04
x1             0.3267      0.138      2.371      0.022       0.049       0.604
x2          2034.6223    267.872      7.596      0.000    1495.424    2573.820
x3          1384.4654   4653.309      0.298      0.767   -7982.161    1.08e+04
==============================================================================
Omnibus:                        5.262   Durbin-Watson:                   1.157
Prob(Omnibus):                  0.072   Jarque-Bera (JB):                4.544
Skew:                          -0.465   Prob(JB):                        0.103
Kurtosis:                       4.147   Cond. No.                     6.12e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.12e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

The regression output example shows that the x2 predictor variables is statistically significant because their p-values equal 0.000. On the other x3 is not statistically significant because its p-value are 0.767 is greater than the usual significance level of 0.05.

In [26]:

#The regression output example shows that the x2 predictor variables is statistically significant because 
#their p-values equal 0.000. On the other x3 is not statistically significant because its p-value are 0.767 
#is greater than the usual significance level of 0.05

#Look at the highest p-values and remove it. In this condition 
#x3(third  dummy variable has the highest one (0.767)

x_opt=x[:,[0,1,2]]#copy the index 0 to 3 from x in x_opt
regressor_OLS=sm.OLS(endog=y,exog=x_opt.astype(float)).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.578
Model:                            OLS   Adj. R-squared:                  0.560
Method:                 Least Squares   F-statistic:                     32.16
Date:                Wed, 17 May 2023   Prob (F-statistic):           1.58e-09
Time:                        09:24:20   Log-Likelihood:                -579.10
No. Observations:                  50   AIC:                             1164.
Df Residuals:                      47   BIC:                             1170.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.622e+04   1.82e+04      1.441      0.156   -1.04e+04    6.28e+04
x1             0.3273      0.136      2.399      0.020       0.053       0.602
x2          2042.3494    264.012      7.736      0.000    1511.226    2573.473
==============================================================================
Omnibus:                        5.343   Durbin-Watson:                   1.169
Prob(Omnibus):                  0.069   Jarque-Bera (JB):                4.565
Skew:                          -0.485   Prob(JB):                        0.102
Kurtosis:                       4.118   Cond. No.                     5.99e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.99e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [27]:

#Look at the highest p-values and remove it. In this condition 
#x1(first  dummy variable has the highest one (0.020)

x_opt=x[:,[0,2]]#copy the index 0 to 3 from x in x_opt
regressor_OLS=sm.OLS(endog=y,exog=x_opt.astype(float)).fit()
regressor_OLS.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.526
Model:                            OLS   Adj. R-squared:                  0.516
Method:                 Least Squares   F-statistic:                     53.29
Date:                Wed, 17 May 2023   Prob (F-statistic):           2.55e-09
Time:                        09:26:34   Log-Likelihood:                -581.98
No. Observations:                  50   AIC:                             1168.
Df Residuals:                      48   BIC:                             1172.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       6.646e+04   7392.995      8.990      0.000    5.16e+04    8.13e+04
x1          2019.1901    276.598      7.300      0.000    1463.052    2575.328
==============================================================================
Omnibus:                        3.267   Durbin-Watson:                   1.090
Prob(Omnibus):                  0.195   Jarque-Bera (JB):                2.366
Skew:                          -0.304   Prob(JB):                        0.306
Kurtosis:                       3.875   Cond. No.                         49.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

**That’s it. The highest impact variable**